/*
 * This source file was generated by the Gradle 'init' task
 */

//This line changed for pull request
package org.example;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.File;
import java.io.IOException;
import java.util.List;

public class App {
    public static void main(String[] args) {
        ObjectMapper objectMapper = new ObjectMapper();

        try {
            List<Person> people = objectMapper.readValue(new File("path/to/person.json"), new TypeReference<List<Person>>() {});
            List<BlogPost> blogPosts = objectMapper.readValue(new File("path/to/blogPosts.json"), new TypeReference<List<BlogPost>>() {});

            Blog blog = new Blog(blogPosts, people);

            // Call getPostsByAuthorAge and print results
            Integer age = 17;
            List<String> postsByAge = blog.getPostsByAuthorAge(age);
            System.out.println("Blog posts that are by the authors of age " + age + ": " + postsByAge);
            
            // Print total number of blog posts and contributors
            System.out.println("Total no. of blog posts: " + blog.getPosts().size());
            System.out.println("Total no. of contributors: " + blog.getContributors().size());

        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
